# Acknowledgements {-}

At [RCC](http://www.rcc.mass.edu), introductory (general) biology is split into two courses (SCI103, Biology I, and SCI104, Biology II) which are taught over two semesters. The two courses were developed in the 1970s by Prof. Georgia Whitman essentially representing botany (Biology I) and zoology (Biology II). Some 20 years ago, Prof. Kyrsis Rodriguez who served as the biology course coordinator until her retirement reduced the botany content and introduced molecular aspects of biology.

In 2015, the Massachusetts Department of Higher Education with its [MassTransfer Pathways](http://www.mass.edu/masstransfer/) initiative prompted a statewide critical evaluation of the structure and content of foundational courses, such as introductory biology, in order to make these courses eligible for transfer across the Commonwealth amongst public higher education institutions. In 2016, we have been fortunate to receive a large grant from the [Massachusetts Life Sciences Center](http://www.masslifesciences.com) to upgrade and modernize our science labs. We have taken this opportunity to re-structure our courses along the lines of current practice of introductory biology teaching such that the Biology I course introduces the molecular and cellular basis of life, while the Biology II course is focused on the basics of organismal biology. Overall the proposed changes will expose our students to modernized (up-to-date) concepts of biology and thus make them more competitive.

This laboratory manual was inspired by "[Encounters with Life](https://www.amazon.com/Encounters-Life-General-Biology-Laboratory/dp/0895826852)" by Larry J. Scott and Hans F. E. Wachtmeister published by the Morton Publishing Company in Englewood CO. We used that manual at RCC for many years. Progress in the biological sciences is, however, relentless and so over the years, our requirements changed, and we felt that it was best to put together a new manual specifically tailored to our needs.

The creation of this manual was greatly facilitated and owes a major debt to [Wikipedia](https://www.wikipedia.org) and its large number of voluntary contributors. I very liberally copied from many Wikipedia pages and then remixed, edited, adapted and added text. With your continued support and help this manual can only get better over time. I urge you to email me with your criticisms and suggestions at nsucher@rcc.mass.edu. This manual is made available as an open educational resource under [Creative Commons Attribution-Share Alike 3.0 Unported](https://creativecommons.org/licenses/by-sa/3.0/deed.en) United States License for others to do as I did and improve and adapt to specific requirements.

I wish to thank Dr. Hillel Sims, Dean of STEM, for the laboratory safety and microscope videos. Last but not least, I want to thank all lab technicians, my teaching colleagues and our students who work together to translate mere words into an exciting laboratory experience for all of us at RCC.
