# Classical Genetics {-}

[Genetics](https://en.wikipedia.org/wiki/Genetics) is, generally, the study of genes, genetic variation, and heredity. In the first four lab sessions of this course, we will study [classical genetics](https://en.wikipedia.org/wiki/Classical_genetics). This is the oldest form of genetics that began with [Gregor Mendel's](https://en.wikipedia.org/wiki/Gregor_Mendel) experiments that formulated and defined a fundamental biological concept now referred to as Mendelian Inheritance. In the second part of this course, we will learn and apply some of the fundamental techniques of [molecular genetics](https://en.wikipedia.org/wiki/Molecular_genetics).

Classical genetics is the part of genetics that is about the transmission of genetic traits via the acts of [reproduction](https://en.wikipedia.org/wiki/Reproduction). The process by which characteristics are passed down from parents to their offspring is called heredity. In the sense of classical genetics, variation is known as the lack of resemblance in related individuals and can be categorized as discontinuous or continuous. The [phenotype](https://en.wikipedia.org/wiki/Phenotype) is a general term that defines an individual's visible, physical traits. The [genotype](https://en.wikipedia.org/wiki/Genotype) of an offspring is known as its genetic makeup. Mendel was the first to systematically investigate how certain well-defined traits are transmitted from parents to offspring. Mendel's conclusions were largely ignored by the vast majority of scientists at the time. In 1900, however, his work was "re-discovered" by three European scientists, [Hugo de Vries](https://en.wikipedia.org/wiki/Hugo_de_Vries), [Carl Correns](https://en.wikipedia.org/wiki/Carl_Correns), and [Erich von Tschermak](https://en.wikipedia.org/wiki/Erich_von_Tschermak). In 1905, [Wilhelm Johannsen](https://en.wikipedia.org/wiki/Wilhelm_Johannsen) introduced the term *gene* and [William Bateson](https://en.wikipedia.org/wiki/William_Bateson) the term *genetics*. Our understanding of what a *(gene)*[https://en.wikipedia.org/wiki/Gene#Discovery_of_discrete_inherited_units] is has undergone quite a bit of change. Currently, genes are considered to be pieces of DNA that contain information for synthesis of ribonuclec acids (RNAs) that can be directly functional or serve as the intermediate template for a protein that performs a function.


## Review Questions
1. What is the subject of the field of genetics?
2. What does the term phenotype denote?
3. What does the term genotype denote?
2. What is a gene?
