# Course Description

## Instructional Objectives:

At the end of the course, students will be able to

*  	contrast the role of mitosis and meiosis in cellular reproduction in eukaryotes.
*  	describe how the concept of the “gene” has originated and evolved over time.
*  	identify eukaryotic chromosomes and describe their structure and function.
*  	explain how DNA stores information, read the genetic code, and describe how it is translated and transmitted to the offspring.
*  	define genetic mutations and describe how they happen and how they can be prevented and give examples of how they influence the function of cells and can lead to disease.
*  	outline how we can isolate, sequence, manipulate and move DNA between cells and organisms.
*  	define the terms genome and genomics, evaluate genomics-related information and discuss the far-reaching consequences for our society of the use of genomics.
*  	outline molecular mechanisms of gene expression.
*  	give examples of complex traits and discuss current models of their genetic basis.
*  	outline the role of genes in the development of organisms and give some specific examples.
*  	discuss how variation in the types and frequencies of “genes” in organisms and populations forms the substrate for natural selection and evolution.

## Student Learning Outcomes:

At successful completion of the course, students will be able to

*  	describe the molecular and cellular mechanisms explaining why children resemble their parents to a certain degree yet are also distinctly different both from them and (if applicable) their own siblings.
*  	give examples and evaluate the strength of the relationship between specific genes and health disorders.
*  	demonstrate “information literacy” and critically analyze reports describing genetics-related research.
*  	discuss the science underlying purported or real medical and scientific breakthroughs or doomsday scenarios related to the manipulation of cells and organisms at the level of DNA.
*  	articulate and appraise the personal and societal implications of genetic testing and genetic engineering.
*  	embark on the next level of training or start work in the life sciences or related fields.
