# Exonuclease I Digestion And Nested PCR

## Exonuclease I Digestion

Exonucleases are enzymes that work by cleaving nucleotides one at a time from the end (exo) of a polynucleotide chain. A hydrolyzing reaction that breaks phosphodiester bonds at either the 3' or the 5' end occurs. Its close relative is the endonuclease, which cleaves phosphodiester bonds in the middle (endo) of a polynucleotide chain. Exonuclease I (Phosphodiesterase I) hydrolytically removes 5'-nucleotides successively from the 3'-hydroxy termini of 3'-hydroxy-terminated oligonucleotides. We use exonuclease I to digest the oligonucleotide primers from the first PCR reaction so that they will not allow for PCR amplification in the second PCR. After the initial PCR primers have been digested, exonuclease I also needs to be inactivated before it is introduced into fresh PCR reactions to prevent it digesting the nested PCR primers.

## Experimental Procedures

1. Add 1 µl of exonuclease I to each tube from the first round of PCR. 
2. Mix well by pipetting up and down.
2. Program the thermocycler to incubate at 37 °C for 15 min.
2. Put the tubes in the thermocycler.
2. Incubate at 37 °C for 15 min.
2. Program the thermocycler to incubate at 80 °C for 15 min.
3. Incubate at 80 °C for 15 min to heat-inactivate the exonuclease I enzyme.

## Nested polymerase chain reaction

Nested polymerase chain reaction (Nested PCR) is a modification of polymerase chain reaction intended to reduce non-specific binding in products due to the amplification of unexpected primer binding sites.

Nested polymerase chain reaction involves two sets of primers, used in two successive runs of polymerase chain reaction, the second set intended to amplify a secondary target within the first run product. This allows amplification for a low number of runs in the first round, limiting non-specific products. The second nested primer set should only amplify the intended product from the first round of amplification and not non-specific product. This allows running more total cycles while minimizing non-specific products. This is useful for very rare templates or PCR with high background.

## Experimental Procedures

1. Obtain and label one microcentrifuge tube for each of the two exonuclease-treated first-round PCR tubes.
5. To dilute each first-round PCR sample 50× (to 1/50 the original concentration), add 98 µl of sterile water into each of the labeled microcentrifuge tubes.
6. Using a fresh tip each time, pipet 2 µl of each first-round PCR into the corresponding microcentrifuge tube containing 98 µl water. Close the cap.
7. Vortex or flick the tube with your finger to mix. Spin briefly in a microfuge to collect the liquid at the bottom of the tube.
8. Label 5 fresh PCR tubes with numbers 6 to 10 and your initials. 
9. Place them in PCR tube adaptors on ice. 
9. Pipet 20 µl of the yellow 2× MMNP into each of the five PCR tubes.
5. Using a fresh pipette tip, add 20 µl of the appropriate DNA template listed in Table \@ref(tab:nestedtubes) to each PCR tube. Gently pipet up and down to mix the reagents.
1. Place the PCR tubes into the thermal cycler.
1. The PCR will run for the next several hours using the Nested GAPDH PCR program listed in Table \@ref(tab:nestedpcr).
1. The laboratory technicians will remove the PCR tubes from the thermocycler after the PCR has finished and store the tubes at -20 °C until we continue our experiments next week.

Table: (\#tab:nestedtubes) Number and content of the tubes for the nested PCR.

|Tube #|Description        |Diluted first-round PCR product|Amount|
|:-----|:------------------|:------------------------------|:-----|
|6     |Negative control   |ddH_2_O         |20 µl  | 
|7     |Positive control   |pGAP plasmid    |20 µl  |
|8     |Arabidopsis gDNA   |Arabidopsis gDNA|20 µl  |
|9     |Extracted plant DNA|gDNA 1          |20 µl  |
|10    |Extracted plant DNA|gDNA 2          |20 µl  |

Table: (\#tab:nestedpcr) PCR protocol for second round (nested) GAPDH amplification.

|PCR Step            |Temperature|Time  |Number of cycles
|:-------------------|:----------|:-----|:--------------
|Initial denaturation|95 °C       |5 min |1
|Denaturation        |95 °C       |1 min |40
|Annealing           |52 °C       |1 min |40
|Extension           |72 °C       |2 min |40
|Final extension     |72 °C       |6 min |1
|Hold                |15 °C       |hold  |

## Review Questions

1. What is an exonuclease?
2. What is nested PCR?

