# DNA sequencing

DNA sequencing is the process of determining the precise order of nucleotides within a DNA molecule. It includes any method or technology that is used to determine the order of the four bases—adenine, guanine, cytosine, and thymine—in a strand of DNA. The advent of rapid DNA sequencing methods has greatly accelerated biological and medical research and discovery.

Knowledge of DNA sequences has become indispensable for basic biological research, and in numerous applied fields such as medical diagnosis, biotechnology, forensic biology, virology and biological systematics. The rapid speed of sequencing attained with modern DNA sequencing technology has been instrumental in the sequencing of complete DNA sequences, or genomes of numerous types and species of life, including the human genome and other complete DNA sequences of many animal, plant, and microbial species.

The first DNA sequences were obtained in the early 1970s by academic researchers using laborious methods based on two-dimensional chromatography. [Frederick Sanger](https://en.wikipedia.org/wiki/Frederick_Sanger) published a method for "DNA sequencing with chain-terminating inhibitors" in 1977. [Walter Gilbert](https://en.wikipedia.org/wiki/Walter_Gilbert) and [Allan Maxam](https://en.wikipedia.org/wiki/Allan_Maxam) at Harvard also developed sequencing methods, including one for "DNA sequencing by chemical degradation". The chain-termination method developed by Frederick Sanger and coworkers in 1977 soon became the method of choice, owing to its relative ease and reliability. When invented, the chain-terminator method used fewer toxic chemicals and lower amounts of radioactivity than the Maxam and Gilbert method. Because of its comparative ease, the Sanger method was soon automated and was the method used in the first generation of DNA sequencers.

Sanger sequencing is the method which prevailed from the 1980s until the mid-2000s. Over that period, great advances were made in the technique, such as fluorescent labelling, capillary electrophoresis, and general automation. Advancements in sequencing were aided by the concurrent development of recombinant DNA technology, allowing DNA samples to be isolated from sources other than viruses.Following the development of fluorescence-based sequencing methods with a DNA sequencer, DNA sequencing has become easier and orders of magnitude faster. High-throughput (formerly "next-generation") sequencing applies to genome sequencing, genome resequencing, transcriptome profiling (RNA-Seq), DNA-protein interactions (ChIP-sequencing), and epigenome characterization.

The high demand for low-cost sequencing has driven the development of high-throughput sequencing technologies that parallelize the sequencing process, producing thousands or millions of sequences concurrently. High-throughput sequencing technologies are intended to lower the cost of DNA sequencing beyond what is possible with standard dye-terminator methods. In ultra-high-throughput sequencing as many as 500,000 sequencing-by-synthesis operations may be run in parallel.

## Experimental Procedures

Each team will be assigned a group of wells on a 96-well plate for setting up the sequencing reactions.  The rows and columns of the  96-well plate are by letters and numbers. The top left well is designated A1 and the bottom right well is H12.

1. Choose two of your plasmid minipreps to sequence.
2. Plan your experiment. You will prepare four sequencing samples for each of your two plasmid minipreps. You will combine each plasmid miniprep with each of the four different sequencing primers — two forward primers and two reverse primers — to ensure complete coverage of the insert. pJET SEQ F and pJET SEQ R anneal to the pJET1.2 vector, while GAP SEQ F and GAP SEQ R are degenerate primers homologous to internal GAPC sequences.
Enter in Table \@ref(tab:seq) below which plasmid was combined with which primer and added into each well. When you name your sequences (sequence wells), make sure you use the same names when submitting samples to the sequencing facility.
2. In your microcentrifuge tubes, combine 10 µl of the miniprep DNA with 1 µl of sequencing primer. Pipet up and down to mix.
3. Pipet 10 µl of the plasmid/primer mixtures into the assigned wells of the 96-well plate. Write down the barcode number from the 96-well plate.
4. Once the entire class has added samples to the plate, seal the plate using the sealing film provided. Ensure a secure seal by rubbing extensively over the top of the plate with a gloved finger. It is essential to seal the plate completely so that the samples are not lost during transit.
5. Go to www.operon.com/bio-rad and fill out the sequencing request form.
6. The laboratory technicians will mail the plate to the sequencing facility.  

Table: (\#tab:seq) DNA Sequencing Reactions

|Well Identifier|Plasmid Name|Sequencing Primers and Color
|:--------------|:-----------|:---------------------------
|		|	     |		
|		|	     |		
|		|	     |		
|		|	     |		
|		|	     |		
|		|	     |		
|		|	     |		
|		|	     |		

